siteConfig:
  lang: en
  title: cottage
  description: A humble homepage of sorts...
  generatorUrl: https://saber.land
  generatorTitle: Static-site generator for Vue
  generatorName: Saber
  hostUrl: https://netlify.com
  hostTitle: Super-powers for static sites!
  hostName: Netlify
  repoLink: https://github.com/andreasvirkus/cottage

permalinks:
  page: /:slug/

build:
  extractCSS: true

plugins:
  - resolve: saber-plugin-query-posts
  - resolve: saber-plugin-prismjs
  - resolve: saber-plugin-search
  - resolve: saber-plugin-google-analytics
    options:
      trackId: 'UA-99596348-1'
  - resolve: saber-plugin-code-copy
    options:
      buttonStyle:
        border: 'none'
